export default {
  list: [
    {
      name: '企业股东',
      icon: 'gudong',
      color: 'green',
      columns: [
        {
          label: '序号',
          prop: 'index',
          width: { width: '7%' },
        },
        {
          label: '姓名',
          prop: 'lpName',
          width: { width: '7%' },
        },
        {
          label: '企业名称',
          prop: 'entName',
          width: { width: '13%' },
        },
        {
          label: '企业注册号',
          prop: 'regNo',
          width: { width: '10%' },
        },
        {
          label: '注册资本（万元）',
          prop: 'regCap',
          width: { width: '13%' },
        },
        {
          label: '币种',
          prop: 'regCapCur',
          width: { width: '10%' },
        },
        {
          label: '出资比例',
          prop: 'fundedRatio',
          width: { width: '10%' },
        },
        {
          label: '省份',
          prop: 'regOrgProvince',
          width: { width: '10%' },
        },
        {
          label: '成立时间',
          prop: 'esDate',
          width: { width: '10%' },
        },
        {
          label: '企业状态',
          prop: 'entStatus',
          width: { width: '10%' },
        },
      ],
      data: [],
    },
    {
      name: '企业法定代表人',
      icon: 'daibiaoren',
      color: 'blue',
      columns: [
        {
          label: '序号',
          prop: 'index',
          width: { width: '10%' },
        },
        {
          label: '查询姓名',
          prop: 'name',
          width: { width: '10%' },
        },
        {
          label: '企业名称',
          prop: 'entName',
          width: { width: '20%' },
        },
        {
          label: '企业注册号',
          prop: 'regNo',
          width: { width: '15%' },
        },
        {
          label: '企业类型',
          prop: 'entType',
          width: { width: '10%' },
        },
        {
          label: '注册资本（万元）',
          prop: 'regCap',
          width: { width: '15%' },
        },
        {
          label: '币种',
          prop: 'regCapCur',
          width: { width: '10%' },
        },
        {
          label: '企业状态',
          prop: 'entStatus',
          width: { width: '10%' },
        },
      ],
      data: [],
    },
    {
      name: '企业主要管理人员',
      icon: 'guanliren',
      color: 'purple',
      columns: [
        {
          label: '序号',
          prop: 'index',
          width: { width: '10%' },
        },
        {
          label: '企业名称',
          prop: 'entName',
          width: { width: '15%' },
        },
        {
          label: '企业注册号',
          prop: 'regNo',
          width: { width: '20%' },
        },
        {
          label: '企业类型',
          prop: 'entType',
          width: { width: '10%' },
        },
        {
          label: '注册资本（万元）',
          prop: 'regCap',
          width: { width: '15%' },
        },
        {
          label: '币种',
          prop: 'regCapCur',
          width: { width: '10%' },
        },
        {
          label: '企业状态',
          prop: 'entStatus',
          width: { width: '10%' },
        },
        {
          label: '职务',
          prop: 'position',
          width: { width: '10%' },
        },
      ],
      data: [],
    },
    {
      name: '开庭公告',
      icon: 'fanzui',
      color: '',
      columns: [
        {
          label: '序号',
          prop: 'index',
          width: { width: '7%' },
        },
        {
          label: '案号',
          prop: 'case_no',
          width: { width: '13%' },
        },
        {
          label: '案由',
          prop: 'case_reason',
          width: { width: '15%' },
        },
        {
          label: '承办部门',
          prop: 'department',
          width: { width: '15%' },
        },
        {
          label: '开庭时间',
          prop: 'hearing_date',
          width: { width: '15%' },
        },
        {
          label: '原告/上诉人',
          prop: 'plaintiff',
          width: { width: '15%' },
        },
        {
          label: '被告/上诉人',
          prop: 'defendant',
          width: { width: '15%' },
        },
      ],
      data: [],
      operate: true,
    },
    {
      name: '裁判文书',
      icon: 'zhongdianrenyuan',
      color: '',
      columns: [
        {
          label: '序号',
          prop: 'index',
          width: { width: '7%' },
        },
        {
          label: '裁判文书类型',
          prop: 'type',
          width: { width: '13%' },
        },
        {
          label: '案件名称',
          prop: 'title',
          width: { width: '20%' },
        },
        {
          label: '判断时间',
          prop: 'pub_date',
          width: { width: '10%' },
        },
        {
          label: '案号',
          prop: 'case_no',
          width: { width: '15%' },
        },
        {
          label: '案由',
          prop: 'case_cause',
          width: { width: '10%' },
        },
        {
          label: '角色',
          prop: 'role',
          width: { width: '10%' },
        },
        {
          label: '请求标的',
          prop: 'sub_amount',
          width: { width: '10%' },
        },
      ],
      data: [],
      operate: true,
    },
  ],
  example: {
    execInfo: [
      {
        creditCode: '9132********LEGM7P',
        entId: '320000u00014b********121000021856',
        entName: '丰*********有限公司',
        entStatus: '在营（开业）',
        entType: '有限责任公司',
        esDate: '2020-09-30',
        lpName: '王*',
        name: '王*',
        position: '执行董事',
        regCap: '6650.000000',
        regCapCur: '人民币元',
        regNo: '3203********408',
        regOrgCity: '**省**市',
        regOrgCityCode: '320300',
        regOrgDistrict: '**省**市*县',
        regOrgProvince: '**省',
      },
    ],
    legalPersonInfo: [
      {
        creditCode: '9132********LEGM7P',
        entId: '320000u00014bd********916121000021856',
        entName: '丰*********有限公司',
        entStatus: '在营（开业）',
        entType: '有限责任公司',
        entityType: '1',
        esDate: '2020-09-30',
        name: '王*',
        regCap: '6650.000000',
        regCapCur: '人民币元',
        regNo: '3203********408',
        regOrgCity: '**省**市',
        regOrgCityCode: '320300',
        regOrgDistrict: '**省**市*县',
        regOrgProvince: '**省',
      },
    ],
    shareholderInfo: [
      {
        conform: '货币',
        creditCode: '9131********02KE44',
        currency: '人民币元',
        entId: '310000u00015E90F********1014532500230118',
        entName: '上海******有限公司',
        entStatus: '在营（开业）',
        entType: '股份有限公司(非上市、自然人投资或控股)',
        esDate: '2017-11-20',
        fundedRatio: '38.59%',
        lpName: '王*',
        name: '王*',
        regCap: '793.900000',
        regCapCur: '人民币元',
        regNo: '3102********068',
        regOrgCity: '**市',
        regOrgCityCode: '310000',
        regOrgDistrict: '**市**新区',
        regOrgProvince: '**市',
        subAmount: '306.377800',
      },
    ],
    openCourtSession: {
      code: 0,
      desc: '成功',
      result: [
        {
          court: '汕三法庭',
          hearing_date: '2020:00',
          case_no: '（20号',
          case_reason: '知权纠纷',
          department: '-',
          judge: '-',
          plaintiff: '小司',
          defendant: '李',
          disabled: '0',
        },
        {
          court: '汕三法庭',
          hearing_date: '2020:00',
          case_no: '（20号',
          case_reason: '知权纠纷',
          department: '-',
          judge: '-',
          plaintiff: '小司',
          defendant: '李',
          disabled: '0',
        },
        {
          court: '汕三法庭',
          hearing_date: '2020:00',
          case_no: '（20号',
          case_reason: '知权纠纷',
          department: '-',
          judge: '-',
          plaintiff: '小司',
          defendant: '李',
          disabled: '0',
        },
        {
          court: '汕三法庭',
          hearing_date: '2020:00',
          case_no: '（20号',
          case_reason: '知权纠纷',
          department: '-',
          judge: '-',
          plaintiff: '小司',
          defendant: '李',
          disabled: '0',
        },
      ],
    },
    refereeDocuments: {
      code: 0,
      desc: '成功',
      result: [
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
        {
          id: '605362',
          type: '行政案件',
          title: '小政判决书',
          date: '2021-03-10',
          case_no: '（27750号',
          case_cause: '其他',
          role: '上诉告）',
          disabled: '0',
          court: '北京',
          case_type: 'D00',
          sub_amount: '0',
          pub_date: '2021-03-18',
        },
      ],
    },
  },
}
