import type { TableColumnData } from '@arco-design/web-vue'

export default {
  table: {
    columns: [
      {
        title: '债权编号',
        dataIndex: 'debt_no',
        slotName: 'debt_no',
        width: 120,
        ellipsis: true,
        tooltip: true,
        fixed: 'left',
      },
      {
        title: '借款合同编号',
        dataIndex: 'contract_no',
        width: 120,
        ellipsis: true,
        tooltip: true,
        fixed: 'left',
      },
      {
        title: '最新动态',
        dataIndex: 'follow',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '所属资产包',
        dataIndex: 'project_name',
        slotName: 'project_name',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '主债权人',
        dataIndex: 'main_debtor_name',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '原始债务人',
        dataIndex: 'origin_debtor_name',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '借款合同金额',
        dataIndex: 'loan_contract_amount',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '借据金额',
        dataIndex: 'iou_amount',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '债权本金余额',
        dataIndex: 'debt_principal_balance',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '利、罚息额度',
        dataIndex: 'interest_penalty_amount',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '本息合计',
        dataIndex: 'principal_interest_amount',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '借款日期',
        dataIndex: 'loan_date',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '利息暂计日期',
        dataIndex: 'interest_pause_date',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '逾期日期',
        dataIndex: 'overdue_date',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '罚息利率',
        dataIndex: 'penalty_interest_rate',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '本债权转让价格',
        dataIndex: 'debt_transfer_price',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '诉讼情况',
        dataIndex: 'lawsuits_condition',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '是否超出诉讼时效',
        dataIndex: 'lawsuits_validity',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '生效法律文书',
        dataIndex: 'lawsuits_body',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '是否超出申请执行时效',
        dataIndex: 'execute_validity',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '执行管辖法院',
        dataIndex: 'executive_court',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '执行现状',
        dataIndex: 'executive_current',
        width: 120,
        ellipsis: true,
        tooltip: true,
      },
      {
        title: '操作',
        dataIndex: 'options',
        slotName: 'options',
        width: 120,
        fixed: 'right',
      },
    ] as TableColumnData[],
  },
  form: {
    model: {
      debt_no: '',
      contract_no: '',
      asset_package_id: '',
      debt_type: '',
      main_debtor_name: '',
      origin_debtor_name: '',
      loan_contract_amount: 0,
      iou_amount: 0,
      area_name: '',
      debt_principal_balance: 0,
      interest_penalty_amount: 0,
      principal_interest_amount: 0,
      loan_date: '',
      overdue_date: '',
      loan_term_rate: 0,
      interest_pause_date: '',
      penalty_interest_rate: 0,
      debt_transfer_price: 0,
      project_level: '',
    },
    rules: {
      project_name: [{ request: true, message: '请输入资产包名称' }],
    },
  },
}
