import type { Debt } from '@/api/interface'
import type { TableColumnData } from '@arco-design/web-vue'

export default {
  table: {
    columns: [
      {
        title: '标题',
        dataIndex: 'lawsuits_title',
      },
      {
        title: '内容摘要',
        dataIndex: 'lawsuits_body',
      },
      {
        title: '审结日期',
        dataIndex: 'trial_date',
      },
      {
        title: '可信度',
        dataIndex: 'match_ratio',
        slotName: 'match_ratio',
      },
      {
        title: '操作',
        dataIndex: 'options',
        slotName: 'options',
        width: 120,
        ellipsis: true,
        tooltip: true,
        fixed: 'right',
      },
    ] as TableColumnData[],
  },
  form: {
    model: {
      asset_debt_id: 0,
      lawsuits_title: '',
      lawsuits_body: '',
      trial_date: '',
      jurisdiction_court: '',
      execute_condition: '',
      execute_validity: '',
      executive_court: '',
      executive_current: '',
    } as Debt.ReqCreateLawsuitsParams,
  },
  description: {
    cpws: {
      title: '标题',
      caseNo: '案号',
      court: '法院名称',
      judge: '审判员',
      yiju: '依据',
      sortTime: '审结日期',
      trialProcedure: '审理状态',
      judgeResult: '判决结果',
      body: '内容',
      partys: '当事人',
    } as { [key: string]: string },
    zxgg: {
      title: '标题',
      sign: '状态',
      caseNo: '案号',
      court: '法院名称',
      proposer: '申请人',
      address: '地址',
      sortTime: '立案日期',
      closeDate: '终本日期',
      yjdw: '依据单位',
      yjCode: '依据文书',
      partys: '当事人',
    } as { [key: string]: string },
    shixin: {
      caseNo: '案号',
      sign: '状态',
      court: '法院名称',
      postTime: '发布时间',
      sortTime: '立案时间',
      yjdw: '依据单位',
      yjCode: '依据文书',
      yiwu: '义务',
      body: '内容',
      partys: '当事人',
    } as { [key: string]: string },
    ktgg: {
      title: '标题',
      caseNo: '案号',
      court: '法院名称',
      courtroom: '法庭名称',
      judge: '法官',
      organizer: '组织者',
      ktggId: '开庭日期',
      sortTime: '开庭时间',
      body: '内容',
      partys: '当事人',
    } as { [key: string]: string },
    fygg: {
      title: '标题',
      caseNo: '案号',
      court: '法院名称',
      sortTime: '立案时间',
      layout: '版面',
      body: '内容',
      partys: '当事人',
    } as { [key: string]: string },
    ajlc: {
      title: '标题',
      caseNo: '案号',
      court: '法院名称',
      sortTime: '组织者',
      sortTime1: '立案时间',
      actionObject: '诉讼标的',
      body: '内容',
      partys: '当事人',
    } as { [key: string]: string },
    bgt: {
      title: '标题',
      sign: '状态',
      caseNo: '案号',
      court: '法院名称',
      courtRankT: '法院等级',
      proposer: '申请人',
      sortTime: '立案时间',
      yjCode: '依据文书',
      yiju: '依据',
      body: '内容',
      partys: '当事人',
    },
  } as { [key: string]: any },
}
